### PR TITLE
9 dec workshop

### PR DESCRIPTION
**Pull request by sympatheticmoose**

### CODE REVIEW

**Comment by bigkevmcd** [comment]
You probably want to fix https://github.com/weaveworks/weave-gitops-docs/blob/0529d2f6258234b2a1785d35ce6dd77ddeb59427/docs/getting-started.md too

**Comment by sympatheticmoose** [comment]
@bigkevmcd I have in a larger update https://github.com/weaveworks/weave-gitops-docs/pull/162

**Review by bigkevmcd — APPROVED** [review]
I'm ok with this subject to #162 being merged.

I think this should've been added to #162

**Comment by sympatheticmoose** [comment]
162 is pretty chunky for someone to review and only impacts users looking at the `main` version of the docs currently which isn't the default. Wanted to get this smaller one in as simpler and quickly advertises to those on the most recent version of the docs (0.4.1)

**Pull request merged**
